"""Shared execution-contract constants for Agentic Arena."""

AGENTIC_MIN_OUTPUT_TOKENS = 2500
AGENTIC_MAX_OUTPUT_TOKENS = 5000

CHATBOT_MAX_OUTPUT_TOKENS = 2048
UI_GUIDE_CHAT_DEFAULT_TOKENS = 512

UI_GUIDE_PRIMARY_MODEL_KEY = "ling_3_0_flash_vl_free"
UI_GUIDE_FAILOVER_MODEL_KEY = "mistral_small_3_2_24b"
UI_GUIDE_ALLOWED_MODEL_KEYS = (
    UI_GUIDE_PRIMARY_MODEL_KEY,
    UI_GUIDE_FAILOVER_MODEL_KEY,
)

UI_GUIDE_FAILOVER_HTTP_STATUSES = (
    404,
    408,
    429,
    500,
    502,
    503,
    504,
)
